typo

diff --git a/etc/init/greins b/etc/init/greins
--- a/etc/init/greins
+++ b/etc/init/greins
@@ -130,7 +130,7 @@ reload() {
     if [ $retval -eq 0 ]; then
         log_success_msg "done"
     else
-        log_error_msg "problem: killproc returned error code $?"
+        log_failure_msg "problem: killproc returned error code $?"
     fi
     return $retval
 }
